langauage: ruby
script: "script/cibuild"
rvm:
  - 2.1
before_install:
  - sudo apt-get install python-software-properties
  - sudo add-apt-repository -y ppa:libreoffice/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq libreoffice-writer

addons:
  code_climate:
    repo_token: 5d3c17f575317e4b908b8af9e1e44fbc48a4970b14a06c086658c3f1e567b558

cache:
  - bundler
  - apt

env:
  global:
    NOKOGIRI_USE_SYSTEM_LIBRARIES=true
