langauage: ruby
script: "script/cibuild"
rvm:
  - 2.1
before_install:
  - sudo add-apt-repository -y ppa:libreoffice/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq libreoffice-writer
  - "soffice --version"
  - "which soffice"
